Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "manager" do |manager|
        manager.vm.synced_folder ".", "/vagrant", disabled: true
        manager.vbguest.no_remote = true
        manager.vbguest.auto_update = false
        manager.vm.network "public_network", ip: "192.168.1.20"
        manager.vm.provider "virtualbox" do |v|     
            v.memory= 1024
            v.cpus = 1
            v.name = "manager"
        end
    end

    config.vm.define "worker" do |worker|
        worker.vm.box = "ubuntu/focal64"
        worker.vm.synced_folder ".", "/vagrant", disabled: true
        worker.vbguest.no_remote = true
        worker.vbguest.auto_update = false
        worker.vm.network "public_network", ip: "192.168.1.21"
        worker.vm.provider "virtualbox" do |v|     
            v.memory= 1024
            v.cpus = 1
            v.name = "worker"
        end
    end
 
end