Vagrant.configure("2") do |config|
 
    #RUNDECK
    config.vm.define "rundeck" do |rundeck|
        rundeck.vm.box = "centos/8"
        rundeck.vm.synced_folder ".", "/vagrant", disabled: true
        rundeck.vbguest.no_remote = true
        rundeck.vbguest.auto_update = false
        rundeck.vm.network "public_network", ip: "192.168.2.12"
        rundeck.vm.provider "virtualbox" do |v|
            v.check_guest_additions = false
            v.memory= 2048
            v.cpus = 1
            v.name = "rundeck"
        end  
    end   
end