---
- name: Definição localhost
  hosts: localhost
  connection: local 
  tasks:
    - name: "Adiciona o repositório docker"
      become: true
      shell:  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: "Instalação do docker-ce, docker-ce-cli, containerd.io"
      become: true
      yum:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        state: latest

    - name: "Confirma se o  docker-ce, docker-ce-cli, containerd.io está instalado"
      become: true
      yum:
        name:  ["docker-ce", "docker-ce-cli", "containerd.io"]
        state: present