---
- name: Definição localhost
  hosts: localhost
  connection: local 
  tasks:
    - name: "Cria o caminho"
      become: true
      shell:  mkdir -p /etc/systemd/system/docker.service.d/

    - name: "Copia o arquivo override.conf"
      become: true
      shell:  cp -a /vagrant/docker/override.conf /etc/systemd/system/docker.service.d/

    - name: "Reload no daemon"
      become: true
      shell: systemctl daemon-reload

    - name: "Restart no serviço docker"
      become: true
      shell: systemctl restart docker.service

    # - name: "Adiciona o daemon docker"
    #   become: true
    #   shell:  |
    #     cat <<EOF > /etc/docker/daemon.json
    #     {
    #       "hosts": ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2375"]
    #     }
    #     EOF