Vagrant.configure("2") do |config|
    
#GITLAB
    config.vm.define "gitlab" do |gitlab|
        gitlab.vm.box = "centos/8"
        gitlab.vm.synced_folder ".", "/vagrant", disabled: true
        gitlab.vbguest.no_remote = true
        gitlab.vbguest.auto_update = false
        gitlab.vm.network "public_network", ip: "192.168.1.11"
        gitlab.vm.provider "virtualbox" do |v|
            v.check_guest_additions = false
            v.memory= 4096
            v.cpus = 1
            v.name = "gitlab"
        end
    end
