[template]
src = "Vagrantfile.tmpl"
dest = "/tmp/confd/vagrant/dockercluster/Vagrantfile"
keys = [
    "/name/machine/3",
    "/cpu/machine/3",
    "/ram/machine/3",
    "/ip/machine/3",
    "/name/machine/4",
    "/cpu/machine/4",
    "/ram/machine/4",
    "/ip/machine/4",
    "/name/machine/5",
    "/cpu/machine/5",
    "/ram/machine/5",
    "/ip/machine/5",
    "/network/adapter",
]