Vagrant.configure("2") do |config|
    
    #dockermanager
    config.vm.define "manager" do |manager|
        manager.vm.box = "ubuntu/focal64"
        manager.vm.synced_folder ".", "/vagrant", disabled: true
        manager.vbguest.no_remote = true
        manager.vbguest.auto_update = false
        manager.vm.network "public_network", ip: "192.168.1.20"
        manager.vm.provider "virtualbox" do |v|     
            v.memory= 1024
            v.cpus = 1
            v.name = "manager"
        end
    end

    #dockerworker01
    config.vm.define "worker01" do |worker01|
        worker01.vm.box = "ubuntu/focal64"
        worker01.vm.synced_folder ".", "/vagrant", disabled: true
        worker01.vbguest.no_remote = true
        worker01.vbguest.auto_update = false
        worker01.vm.network "public_network", ip: "192.168.1.21"
        worker01.vm.provider "virtualbox" do |v|     
            v.memory= 1024
            v.cpus = 1
            v.name = "worker01"
        end
    end

    #dockerworker02
    config.vm.define "worker02" do |worker02|
        worker02.vm.box = "ubuntu/focal64"
        worker02.vm.synced_folder ".", "/vagrant", disabled: true
        worker02.vbguest.no_remote = true
        worker02.vbguest.auto_update = false
        worker02.vm.network "public_network", ip: "192.168.1.22"
        worker02.vm.provider "virtualbox" do |v|     
            v.memory= 1024
            v.cpus = 1
            v.name = "worker02"
        end
    end

    #JENKINS
    config.vm.define "jenkins" do |jenkins|
        jenkins.vm.box = "centos/8"
        jenkins.vm.synced_folder ".", "/vagrant", disabled: true
        jenkins.vbguest.no_remote = true
        jenkins.vbguest.auto_update = false
        jenkins.vm.network "public_network", ip: "192.168.1.10"
        jenkins.vm.provider "virtualbox" do |v|
            v.check_guest_additions = false
            v.memory= 4096
            v.cpus = 1
            v.name = "jenkins"
        end
    end


    #GITLAB
    config.vm.define "gitlab" do |gitlab|
        gitlab.vm.box = "centos/8"
        gitlab.vm.synced_folder ".", "/vagrant", disabled: true
        gitlab.vbguest.no_remote = true
        gitlab.vbguest.auto_update = false
        gitlab.vm.network "public_network", ip: "192.168.1.11"
        gitlab.vm.provider "virtualbox" do |v|
            v.check_guest_additions = false
            v.memory= 4096
            v.cpus = 1
            v.name = "gitlab"
        end
    end

    #RUNDECK
    config.vm.define "rundeck" do |rundeck|
        rundeck.vm.box = "centos/8"
        rundeck.vm.synced_folder ".", "/vagrant", disabled: true
        rundeck.vbguest.no_remote = true
        rundeck.vbguest.auto_update = false
        rundeck.vm.network "public_network", ip: "192.168.1.12"
        rundeck.vm.provider "virtualbox" do |v|
            v.check_guest_additions = false
            v.memory= 2048
            v.cpus = 1
            v.name = "rundeck"
        end  
    end      
  #PWSERVER
    config.vm.define "pwserver" do |pwserver|
        pwserver.vm.box = "ubuntu/focal64"
        pwserver.vm.synced_folder ".", "/vagrant", disabled: true
        pwserver.vbguest.no_remote = true
        pwserver.vbguest.auto_update = false
        pwserver.vm.network "public_network", ip: "192.168.1.13"
        pwserver.vm.provider "virtualbox" do |v|
            v.check_guest_additions = false
            v.memory= 8192
            v.cpus = 4
            v.name = "pwserver"
        end  
    end      
end
