Vagrant.configure("2") do |config|
    config.vm.define "jenkins" do |jenkins|
        jenkins.vm.box = "centos/8"
        jenkins.vm.synced_folder ".", "/vagrant", disabled: true
        jenkins.vbguest.no_remote = true
        jenkins.vbguest.auto_update = false
        jenkins.vm.network "public_network", ip: "192.168.2.10"
        jenkins.vm.provider "virtualbox" do |v|
            v.check_guest_additions = false
            v.memory= 4096
            v.cpus = 1
            v.name = "jenkins"
        end
    end
end