---
- name: Definição localhost
  hosts: localhost
  connection: local 
  tasks:
    - name: "Copia os arquivos"
      become: true
      shell: "cp -a /home/dev/.ssh/* /var/lib/rundeck/.ssh/"

    - name: "da permissão"
      become: true
      shell: "chown -R rundeck:rundeck /var/lib/rundeck/.ssh/"

    - name: "da permissão"
      become: true
      shell: ssh-keygen -p -m PEM -f /var/lib/rundeck/.ssh/id_rsa -N ''
