---
- name: Definição localhost
  hosts: localhost
  connection: local 
  tasks:
    - name: "Cria o caminho"
      become: true
      shell: "mkdir -p /etc/rundeck/nodes/"

    - name: "Copia"
      become: true
      shell: "cp -a /vagrant/rundeck/sourcefile.yaml /etc/rundeck/nodes/"

    - name: "Cria o caminho"
      become: true
      shell: "chown -R rundeck:rundeck /etc/rundeck/nodes/"