---
- name: "Baixar arquivo de repositório Jenkins"
  shell: curl "{{ jenkins_repo }}"> "{{ jenkins_repo_dir }}"

- name: "Importa a chave do repositório do Jenkins"
  shell: rpm --import "{{ jenkins_repo_key }}"

- name: "Adiciona repositório do Jenkins"
  shell: yum-config-manager --add-repo "{{ docker_repo }}"

- name: "Instala updates gerais"
  shell: yum update -y

- name: "Instalar Jenkins e Docker"
  yum:
    name:
      - "{{ jenkins_package }}"
      - "{{ docker_ce_package }}"
      - "{{ docker_ce_cli_package }}"
      - "{{ conainerd_io_package }}"
    state: latest

- name: "Checar as instalações Jenkins e Docker"
  yum:
    name:
      - "{{ jenkins_package }}"
      - "{{ docker_ce_package }}"
      - "{{ docker_ce_cli_package }}"
      - "{{ conainerd_io_package }}"
    state: latest

- name: "Faz restart do serviço do jenkins"
  service:
    name: "{{ jenkins_service }}"
    state: restarted

- name: "Habilitar o serviço do jenkins para restart da máquina"
  systemd:
    name: "{{ jenkins_service }}"
    enabled: yes

- name: "Faz restart do serviço do docker"
  service:
    name: "{{ docker_service }}"
    state: restarted

- name: "Habilitar o serviço do docker para restart da máquina"
  systemd:
    name: "{{ docker_service }}"
    enabled: yes

- name: "Faz restart do serviço do Firewalld"
  service:
    name: "{{ firewall_service }}"
    state: restarted

- name: "Habilitar o serviço do Firewalld para restart da máquina"
  systemd:
    name: "{{ firewall_service }}"
    enabled: yes

- name: "Port 8080 Firewalld"
  shell: firewall-cmd --add-port=8080/tcp --permanent

- name: "Reload Firewalld"
  shell: firewall-cmd --reload

- name: "Permissão docker para usuário {{ jenkins_user }}"
  shell: usermod -aG "{{ docker_group }}" "{{ jenkins_user }}"

- name: "Permissão docker para usuário {{ my_user }} "
  shell: usermod -aG "{{ docker_group }}" "{{ my_user }}"
# - name: "Gerar arquivo {{ jenkins_ssh_path }}/id_rsa"
#   openssh_keypair:
#     path: "{{ jenkins_ssh_path }}/id_rsa"

# - name: "Gerar arquivo {{ jenkins_ssh_path }}/id_rsa.pub"
#   openssh_keypair:
#     path: "{{ jenkins_ssh_path }}/id_rsa.pub"

# - name: "Copiar authorized_keys para o usuário jenkins"
#   become_user: "{{ jenkins_user }}"
#   copy:
#     src: files/authorized_keys
#     dest: "{{ jenkins_ssh_path }}/authorized_keys"
#     owner: "{{ jenkins_user }}"
#     group: "{{ jenkins_user }}"
#     mode: "0700"
