---
# Instalação
- name: "Repositório Jenkins"
  become: true
  shell: curl http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo > /etc/yum.repos.d/jenkins.repo

- name: "Import RPM key"
  become: true
  shell:  rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: "Repositório Jenkins"
  become: true
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: "Instala updates"
  become: true
  shell: yum update -y

- name: "Instalando os pacotes para o [JENKINS]"
  become: true
  yum:
    name: ["jenkins", "docker-ce", "docker-ce-cli", "containerd.io"]
    state: latest

- name: "Checa jenkins"
  become: true
  yum:
    name: ["jenkins", "docker-ce", "docker-ce-cli", "containerd.io"]
    state: latest

- name: "Start Jenkins"
  become: true
  shell: systemctl start jenkins

- name: "Enable Jenkins"
  become: true
  shell: systemctl enable jenkins

- name: "Start Docker"
  become: true
  shell: systemctl start docker

- name: "Enable Docker"
  become: true
  shell: systemctl enable docker

- name: "Start Firewalld"
  become: true
  shell: systemctl start firewalld

- name: "Enable Firewalld"
  become: true
  shell: systemctl enable firewalld

- name: "Port 8080 Firewalld"
  become: true
  shell: firewall-cmd --add-port=8080/tcp --permanent

- name: "Reload Firewalld"
  become: true
  shell:  firewall-cmd --reload

- name: "Permissão docker user Jenkins"
  become: true
  shell:  usermod -aG docker jenkins

- name: "Permissão docker user centos"
  become: true
  shell:  usermod -aG docker centos

  # USER JENKINS
- name: "Permissão docker user centos"
  become: true
  shell:  mkdir -p /home/jenkins/.ssh/

- name: Copy id_rsa
  become: yes
  copy:
    src: files/.ssh/id_rsa
    dest: /home/jenkins/.ssh/id_rsa
    owner: jenkins
    group: jenkins
    mode: '0600'

- name: Copy id_rsa.pub
  become: yes
  copy:
    src: files/.ssh/id_rsa.pub
    dest: /home/jenkins/.ssh/id_rsa.pub
    owner: jenkins
    group: jenkins
    mode: '0600'

- name: Copy authorized_keys
  become: yes
  copy:
    src: files/.ssh/authorized_keys
    dest: /home/jenkins/.ssh/authorized_keys
    owner: jenkins
    group: jenkins
    mode: '0600'

- name: Atualiza permissão /home/jenkins/.ssh/
  become: yes
  shell: chmod 700 -R /home/jenkins/.ssh/

- name: Atualiza permissão /home/jenkins/.ssh/
  become: yes
  shell: chown jenkins:jenkins -R /home/jenkins/.ssh/
