---
- name: "Intalação das aplicações do GitLab"
  yum:
    name:
      - " {{ policycoreutils_package}} "
      - " {{ perl_package}} "
      - " {{ postfix_package}} "
    state: latest
    update_cache: yes

- name: "Verifica a instalação aplicações base do GitLab"
  yum:
    name:
      - "{{ policycoreutils_package }}"
      - "{{ perl_package }}"
      - "{{ postfix_package }}"
    state: present

- name: "Faz start do serviço do Firewalld"
  service:
    name: "{{ firewall_service }}"
    state: started

- name: "Habilitar o serviço do Firewalld para restart da máquina"
  systemd:
    name: "{{ firewall_service }}"
    enabled: yes

- name: "Habilitar o serviço do postfix para restart da máquina"
  systemd:
    name: "{{ postfix_service }}"
    enabled: yes

- name: "Adiciona os serviços http ao firewall"
  shell: firewall-cmd --permanent --add-service=http

- name: "Adiciona os serviços https ao firewall"
  shell: firewall-cmd --permanent --add-service=https

- name: "Reincia o serviço firewalld"
  service:
    name: "{{ firewall_service }}"
    state: restarted

- name: "Reincia o serviço postfix"
  service:
    name: "{{ postfix_service }}"
    state: restarted

- name: "Baixa o script para instalação do GitLab"
  shell: curl "{{ gitlab_script }}" | bash

- name: "Instala o GitLab com a url externa {{ gitlab_url }}"
  shell: EXTERNAL_URL="{{ gitlab_url }}" dnf install -y "{{ gitlab_package }}"
