---
- name: "Instalar aplicações do gitlab"
  yum:
    name:
      - " {{ policycoreutils_package}} "
      - " {{ perl_package}} "
      - " {{ postfix_package}} "
    state: latest
    update_cache: yes

- name: "Instalar aplicações do gitlab"
  yum:
    name:
      - "{{ policycoreutils_package }}"
      - "{{ perl_package }}"
      - "{{ postfix_package }}"
    state: present

- name: "Faz start do serviço do Firewalld"
  service:
    name: "{{ firewall_service }}"
    state: started

- name: "Habilitar o serviço do Firewalld para restart da máquina"
  systemd:
    name: "{{ firewall_service }}"
    enabled: yes

- name: "--add-service=http"
  shell: firewall-cmd --permanent --add-service=http

- name: "--add-service=https"
  shell: firewall-cmd --permanent --add-service=https

- name: "restart firewalld"
  shell: systemctl restart "{{ firewall_service }}"

- name: "Faz restart do serviço do Firewalld"
  service:
    name: "{{ postfix_service }}"
    state: restarted

- name: "Habilitar o serviço do postfix para restart da máquina"
  systemd:
    name: "{{ postfix_service }}"
    enabled: yes

- name: "Download gitlab"
  shell: curl "{{ gitlab_script }}" | bash

- name: "Instala gitlab"
  shell: EXTERNAL_URL="{{ gitlab_url }}" dnf install -y "{{ gitlab_package }}"
