Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
   
    #Update nos repositórios do ubuntu 20.04
    config.vm.provision "shell", inline: "sudo apt update -y"
    #Instala o Ansible para provisionamento da máquina
    config.vm.provision "shell", inline: "sudo apt install -y ansible"
    #Compartilha a pasta ./public para /vagrant
    config.vm.synced_folder "./public", "/vagrant/public", type: 'virtualbox'
    #Desabilita o compartilhamento geral da pasta atual
    config.vm.synced_folder ".", "/vagrant", disabled: true

    #Copia todos os arquivos da pasta /vagrant para o home do vagrant da máquina específica
    #config.vm.provision "shell", inline: "cp -a /vagrant/* /home/vagrant"
    # Docker
    config.vm.define "docker_manager" do |docker_manager|
      docker_manager.vm.provision "shell", inline: "echo docker_manager > /etc/hostname"
      docker_manager.vm.synced_folder "./vms/docker", "/vagrant/docker", type: 'virtualbox'
      docker_manager.vbguest.installer_options = { allow_kernel_upgrade: true }
      docker_manager.vbguest.auto_update = false
      docker_manager.vbguest.no_remote = true
      docker_manager.vm.network "public_network", ip: "10.1.1.20"
      docker_manager.vm.provider "virtualbox" do |v|     
        v.memory= 2048
        v.cpus = 1
        v.name = "docker_manager"
      end
      #Executa a automação do ansible
      docker_manager.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_netplan.yml"
      docker_manager.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_create_user.yml"
      docker_manager.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_install.yml"
      docker_manager.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_servico.yml"
      docker_manager.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_daemon.yml"
      docker_manager.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_servico.yml"
      docker_manager.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_reboot.yml"
    end    
    # Docker
    config.vm.define "docker_worker_1" do |docker_worker_1|
      docker_worker_1.vm.provision "shell", inline: "echo docker_worker_1 > /etc/hostname"
      docker_worker_1.vm.synced_folder "./vms/docker", "/vagrant/docker", type: 'virtualbox'
      docker_worker_1.vbguest.installer_options = { allow_kernel_upgrade: true }
      docker_worker_1.vbguest.auto_update = false
      docker_worker_1.vbguest.no_remote = true
      docker_worker_1.vm.network "public_network", ip: "10.1.1.21"
      docker_worker_1.vm.provider "virtualbox" do |v|     
        v.memory= 2048
        v.cpus = 1
        v.name = "docker_worker_1"
      end
      #Executa a automação do ansible
      docker_worker_1.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_netplan.yml"
      docker_worker_1.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_create_user.yml"
      docker_worker_1.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_install.yml"
      docker_worker_1.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_servico.yml"
      docker_worker_1.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_daemon.yml"
      docker_worker_1.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_servico.yml"
      docker_worker_1.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_reboot.yml"
    end    

    # Docker
    config.vm.define "docker_worker_2" do |docker_worker_2|
      docker_worker_2.vm.provision "shell", inline: "echo docker_worker_2 > /etc/hostname"
      docker_worker_2.vm.synced_folder "./vms/docker", "/vagrant/docker", type: 'virtualbox'
      docker_worker_2.vbguest.installer_options = { allow_kernel_upgrade: true }
      docker_worker_2.vbguest.auto_update = false
      docker_worker_2.vbguest.no_remote = true
      docker_worker_2.vm.network "public_network", ip: "10.1.1.22"
      docker_worker_2.vm.provider "virtualbox" do |v|     
        v.memory= 2048
        v.cpus = 1
        v.name = "docker_worker_2"
      end
      #Executa a automação do ansible
      docker_worker_2.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_netplan.yml"
      docker_worker_2.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_create_user.yml"
      docker_worker_2.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_install.yml"
      docker_worker_2.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_servico.yml"
      docker_worker_2.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_daemon.yml"
      docker_worker_2.vm.provision "shell", inline: "ansible-playbook /vagrant/docker/ansible_docker_servico.yml"
      docker_worker_2.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_reboot.yml"
    end    

    #JENKINS
    config.vm.define "jenkins" do |jenkins|
      jenkins.vm.provision "shell", inline: "echo jenkins > /etc/hostname"
      jenkins.vm.synced_folder "./vms/jenkins", "/vagrant/jenkins", type: 'virtualbox'
      jenkins.vbguest.installer_options = { allow_kernel_upgrade: true }
      jenkins.vbguest.auto_update = false
      jenkins.vbguest.no_remote = true
      jenkins.vm.network "public_network", ip: "10.1.1.30"
      jenkins.vm.provider "virtualbox" do |v|
        v.check_guest_additions = false
        v.memory= 4096
        v.cpus = 1
        v.name = "jenkins"
        end
        #Executa a automação do ansible
        jenkins.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_netplan.yml"
        jenkins.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_create_user.yml"
        jenkins.vm.provision "shell", inline: "ansible-playbook /vagrant/jenkins/ansible_jenkins.yml"
        jenkins.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_reboot.yml"
    end

    #RUNDECK
    config.vm.define "rundeck" do |rundeck|
      rundeck.vm.provision "shell", inline: "echo rundeck > /etc/hostname"
      rundeck.vm.synced_folder "./vms/rundeck", "/vagrant/rundeck", type: 'virtualbox'
      rundeck.vbguest.installer_options = { allow_kernel_upgrade: true }
      rundeck.vbguest.auto_update = false
      rundeck.vbguest.no_remote = true
      rundeck.vm.network "public_network", ip: "10.1.1.32"
      rundeck.vm.provider "virtualbox" do |v|
        v.check_guest_additions = false
        v.memory= 2048
        v.cpus = 1
        v.name = "rundeck"
      end  
      #Executa a automação do ansible
      rundeck.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_netplan.yml"
      rundeck.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_create_user.yml"
      rundeck.vm.provision "shell", inline: "ansible-playbook /vagrant/rundeck/ansible_rundeck.yml"
      rundeck.vm.provision "shell", inline: "ansible-playbook /vagrant/rundeck/ansible_rundeck_ssh.yml"
      rundeck.vm.provision "shell", inline: "ansible-playbook /vagrant/rundeck/ansible_rundeck_nodes.yml"
      rundeck.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_reboot.yml"
    end

    #vpn
    config.vm.define "vpn" do |vpn|
      vpn.vm.provision "shell", inline: "echo vpn > /etc/hostname"
      vpn.vm.synced_folder "./vms/vpn", "/vagrant/vpn", type: 'virtualbox'
      vpn.vbguest.installer_options = { allow_kernel_upgrade: true }
      vpn.vbguest.auto_update = false
      vpn.vbguest.no_remote = true
      vpn.vm.network "public_network", ip: "10.1.1.5"
      vpn.vm.provider "virtualbox" do |v|     
        v.memory= 512
        v.cpus = 1
        v.name = "vpn"
      end
      #Executa a automação do ansible
      vpn.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_netplan.yml"
      vpn.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_create_user.yml"
      vpn.vm.provision "shell", inline: "ansible-playbook /vagrant/vpn/ansible_vpn.yml"
      vpn.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_reboot.yml"
    end
    
    #GITLAB
    config.vm.define "gitlab" do |gitlab|
      gitlab.vm.provision "shell", inline: "echo gitlab > /etc/hostname"
      gitlab.vm.synced_folder "./vms/gitlab", "/vagrant/gitlab", type: 'virtualbox'
      gitlab.vbguest.installer_options = { allow_kernel_upgrade: true }
      gitlab.vbguest.auto_update = false
      gitlab.vbguest.no_remote = true
      gitlab.vm.network "public_network", ip: "10.1.1.31"
      gitlab.vm.provider "virtualbox" do |v|
        v.check_guest_additions = false
        v.memory= 4096
        v.cpus = 1
        v.name = "gitlab"
      end
      #Executa a automação do ansible
      gitlab.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_netplan.yml"
      gitlab.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_create_user.yml"
      gitlab.vm.provision "shell", inline: "ansible-playbook /vagrant/gitlab/ansible_gitlab.yml"
      gitlab.vm.provision "shell", inline: "ansible-playbook /vagrant/public/ansible_reboot.yml"
    end
  end