---
- name: Definição localhost
  hosts: localhost
  connection: local 
  tasks:
    - name: "Update nos pacotes do ubuntu"
      become: true
      shell: apt-get update -y

    - name: "Instalação do bind9"
      become: true
      apt:
        name: ["bind9"]
        state: latest

    - name: "Confirma se o bind9 está instalado"
      become: true
      apt:
        name: bind9
        state: present

    - name: "Copia os arquivos para a pasta"
      become: true
      shell: cp -a /vagrant/dns/bind/* /etc/bind/

    - name: "Reinicia o serviço"
      become: true
      shell: "service bind9 restart"
    
    - name: "Enable no serviço"
      become: true
      shell: "systemctl enable named"