---
- name: Definição localhost
  hosts: localhost
  connection: local 
  tasks:
    - name: "[WORKAROUND (CENTOS 7)]: Altera o DNS da máquina, adiciona 10.1.1.3 e 10.1.1.1"
      become: true
      shell: echo "nameserver 10.1.1.3" > /etc/resolv.conf; echo "nameserver 10.1.1.1" >> /etc/resolv.conf;  chattr +i /etc/resolv.conf;

 