---
- name: "Update repositório ubuntu"
  shell: yum-config-manager --add-repo "{{ docker_repo }}"

- name: "Install Docker Engine"
  yum:
    name:
      - "{{ docker_ce_package }}"
      - "{{ docker_ce_cli_package }}"
      - "{{ containerd_io_package }}"
    state: latest

- name: "Install Docker Engine"
  yum:
    name:
      - "{{ docker_ce_package }}"
      - "{{ docker_ce_cli_package }}"
      - "{{ containerd_io_package }}"
    state: present

- name: "Reload no daemon"
  systemd:
    name: docker.service
    enabled: yes
  # shell: systemctl daemon-reload

- name: "Reload no daemon"
  systemd:
    name: containerd.service
    enabled: yes

- name: "Cria o caminho para o serviço"
  shell: mkdir -p "{{ docker_dir_service }}"
#   file:
#     path: "{{ docker_dir_service }}"
#     owner: "{{ sudo_user }}"
#     group: "{{ sudo_group }}"
#     mode: "0755"

- name: Copy override.conf
  copy:
    src: files/override.conf
    dest: "{{ docker_dir_service }}/override.conf"
    owner: "{{ sudo_user }}"
    group: "{{ sudo_group }}"
    mode: "0755"

- name: restarted
  shell: systemctl daemon-reload

- name: "Restart no serviço docker"
  service:
    name: "{{ docker_service }}"
    state: restarted
  # shell: systemctl restart docker.service

- name: "Restart no serviço docker"
  service:
    name: containerd.service
    state: restarted
  # shell: systemctl restart docker.service

- name: "Adiciona usuário ubuntu ao grupo docker"
  shell: usermod -aG "{{ docker_group }}" "{{ my_user}}"

- name: "Baixa docker-compose 1.29.2"
  shell: curl -L "{{ docker_compose_url }}" -o /usr/local/bin/docker-compose

- name: "Chmod"
  shell: chmod +x "{{ docker_compose_path }}"

- name: "Baixa docker-compose 1.29.2"
  shell: ln -s "{{ docker_compose_path }}" /usr/bin/docker-compose
