---
- name: "Adiciona configuração de repostório"
  shell: yum-config-manager --add-repo "{{ docker_repo }}"

- name: "Instalação dos pacotes necessários para o Docker"
  dnf:
    name:
      - "{{ docker_ce_package }}"
      - "{{ docker_ce_cli_package }}"
      - "{{ containerd_io_package }}"
    state: latest
    update_cache: yes

- name: "Confirma as instalações dos pacotes para o Docker"
  dnf:
    name:
      - "{{ docker_ce_package }}"
      - "{{ docker_ce_cli_package }}"
      - "{{ containerd_io_package }}"
    state: present

- name: "Reinicio do serviço Docker"
  systemd:
    name: "{{ docker_service }}"
    enabled: yes

- name: "Reinicio do serviço containerd"
  systemd:
    name: "{{ containerd_service }}"
    enabled: yes

- name: "Cria o caminho para o serviço systemD"
  shell: mkdir -p "{{ docker_service_path }}"

- name: "Cópia de configuração de escutar na porta 0.0.0.0"
  copy:
    src: files/override.conf
    dest: "{{ docker_service_path }}/override.conf"
    owner: "{{ sudo_user }}"
    group: "{{ sudo_group }}"
    mode: "0755"

- name: "Reincio do daemon para aplicar efeitos"
  shell: systemctl daemon-reload

- name: "Reinicio do serviço Docker"
  service:
    name: "{{ docker_service }}"
    state: restarted

- name: "Reinicio do serviço Containerd"
  service:
    name: "{{ containerd.service }}"
    state: restarted

- name: "Concede permissão {{ docker_group }} ao usuário {{ my_user}}"
  shell: usermod -aG "{{ docker_group }}" "{{ my_user}}"

- name: "Baixa docker-compose 1.29.2"
  shell: curl -L "{{ docker_compose_url }}" -o "{{ docker_compose_path }}"

- name: "Concede permissão de execução ao Compose"
  shell: chmod +x "{{ docker_compose_path }}"

- name: "Criar link para execução do Compose"
  shell: ln -s "{{ docker_compose_path }}" /usr/bin/docker-compose
