---
- name: "Update repositório ubuntu"
  become: true
  shell: apt-get update -y

- name: "Add Docker’s official GPG key"
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: "Add Docker’s official GPG key"
  become: true
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: "Update repositório ubuntu"
  become: true
  shell: apt-get update -y

- name: "Install Docker Engine"
  become: true
  apt: 
    name: ["docker-ce","docker-ce-cli","containerd.io"]
    state: latest

- name: "Cria o caminho para o serviço"
  become: true
  shell:  mkdir -p /etc/systemd/system/docker.service.d/

- name: Copy override.conf
  become: yes
  copy:
    src: files/override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: '0777'

- name: "Reload no daemon"
  become: true
  shell: systemctl daemon-reload

- name: "Restart no serviço docker"
  become: true
  shell: systemctl restart docker.service

- name: "Adiciona usuário ubuntu ao grupo docker"
  become: true
  shell: usermod -aG docker ubuntu
