---
- name: Definição localhost
  hosts: localhost
  connection: local 
  tasks:
    - name: Habilita o serviço docker
      systemd:
        name: docker
        enabled: yes
        masked: no
    - name: Certifica-se que o docker está ativo
      systemd:
        state: started
        name: docker
