---
- name: "Baixa script de instalação do rundeck"
  shell: curl "{{ rundeck_script_file }} " 2> /dev/null | bash -s rundeck

- name: "Instalação do {{ rundeck_package }}"
  dnf:
    name:
      - "{{ rundeck_package }}"
    state: latest
    update_cache: yes

- name: "Verifica a instalação {{ rundeck_package }}"
  dnf:
    name:
      - "{{ rundeck_package }}"
    state: present

- name: "Comenta linha de filesystem no arquivo {{ rundeck_properties_file }}"
  shell: sed -i '/projectsStorageType/s/^/#/g' "{{ rundeck_properties_file }}"

- name: "Adiciona filesystem no arquivo {{ rundeck_properties_file }}"
  shell: echo "rundeck.projectsStorageType=filesystem" >> "{{ rundeck_properties_file }}"

- name: "Comenta linha de localhost no arquivo {{ rundeck_properties_file }}"
  shell: sed -i '/localhost/s/^/#/g' "{{ rundeck_properties_file }}"

- name: "Adiciona o {{ rundeck_host }} no arquivo {{ rundeck_properties_file }}"
  shell: echo "grails.serverURL={{ rundeck_host }}" >> "{{ rundeck_properties_file }}"

- name: "Faz restart do serviço do rundeck"
  service:
    name: "{{ rundeck_service }}"
    state: restarted

- name: "Habilita o serviço do rundeck para restart"
  systemd:
    name: "{{ rundeck_service }}"
    enabled: yes

- name: "Gerar arquivo {{ rundeck_ssh_path }}/id_rsa"
  openssh_keypair:
    path: "{{ rundeck_ssh_path }}/id_rsa"

- name: "Gerar arquivo {{ rundeck_ssh_path }}/id_rsa.pub"
  openssh_keypair:
    path: "{{ rundeck_ssh_path }}/id_rsa.pub"

- name: "Cópia da chave autorizadas para login id_rsa.pub"
  fetch:
    src: "{{ rundeck_ssh_path }}/id_rsa.pub"
    dest: files/id_rsa.pub

- name: "Concede permissão para a chave em Gerar arquivo {{ rundeck_ssh_path }}/id_rsa"
  shell: "ssh-keygen -p -m PEM -f {{ rundeck_ssh_path }}/id_rsa -N '' "

- name: "Cria o diretório: {{ rundeck_node_path }}"
  file:
    path: "{{ rundeck_node_path }}"
    owner: "{{ rundeck_user }}"
    group: "{{ rundeck_user }}"
    mode: "0750"
    remote_src: yes
    state: directory

- name: "Cópia do {{ rundeck_node_path }}/sourcefile.yaml"
  copy:
    src: files/sourcefile.yaml
    dest: "{{ rundeck_node_path }}/sourcefile.yaml"
    owner: "{{ rundeck_user }}"
    group: "{{ rundeck_user }}"
    mode: "0750"
