---
- name: "Baixa script de instalação do rundeck"
  shell: curl "{{ rundeck_script_file }} " 2> /dev/null | bash -s rundeck

- name: "Instalação do {{ rundeck_package }}"
  dnf:
    name:
      - "{{ rundeck_package }}"
    state: latest
    update_cache: yes

- name: "Verifica a instalação {{ rundeck_package }}"
  dnf:
    name:
      - "{{ rundeck_package }}"
    state: present

# - name: Replace before the expression till the begin of the file (requires Ansible >= 2.4)
#   replace:
#     path: "{{ rundeck_properties_file }}"
#     before: "# live site config"
#     regexp: "^(.+)$"
#     replace: '# \1'

- name: "Comenta linha de filesystem no rundeck"
  shell: sed -i '/projectsStorageType/s/^/#/g' "{{ rundeck_properties_file }}"

- name: "Adiciona o hostname no arquivo"
  shell: echo "rundeck.projectsStorageType=filesystem" >> "{{ rundeck_properties_file }}"

- name: "Comenta linha de host no rundeck"
  shell: sed -i '/localhost/s/^/#/g' "{{ rundeck_properties_file }}"

- name: "Adiciona o hostname no arquivo"
  shell: echo "grails.serverURL={{ rundeck_host }}" >> "{{ rundeck_properties_file }}"

- name: restart_rundeck
  service:
    name: "{{ rundeck_service }}"
    state: restarted

- name: restart_rundeck
  systemd:
    name: "{{ rundeck_service }}"
    enabled: yes

- name: Change file ownership, group and permissions
  file:
    path: "{{ rundeck_ssh_path }}"
    remote_src: yes
    owner: "{{ rundeck_user }}"
    group: "{{ rundeck_user }}"
    mode: "0777"

- name: Copy file with owner and permissions
  become_user: "{{ my_user }}"
  copy:
    src: "{{ user_ssh_path }}"
    dest: "{{ rundeck_ssh_path }}"
    remote_src: yes

- name: Change file ownership, group and permissions
  file:
    path: "{{ rundeck_ssh_path }}"
    remote_src: yes
    owner: "{{ rundeck_user }}"
    group: "{{ rundeck_user }}"
    mode: "0754"

- name: "da permissão"
  shell: "ssh-keygen -p -m PEM -f {{ rundeck_ssh_path }}/id_rsa -N '' "

- name: Creates directory
  file:
    path: "{{ rundeck_node_path }}"
    remote_src: yes
    state: directory

- name: Copy id_rsa
  copy:
    src: files/sourcefile.yaml
    dest: "{{ rundeck_node_path }}/sourcefile.yaml"
    owner: "{{ rundeck_user }}"
    group: "{{ rundeck_user }}"
    mode: "0754"

- name: Change file ownership, group and permissions
  file:
    path: "{{ rundeck_node_path }}"
    remote_src: yes
    owner: "{{ rundeck_user }}"
    group: "{{ rundeck_user }}"
    mode: "0754"
