---
- name: "Baixa arquivos rundeck"
  become: true
  shell: curl https://raw.githubusercontent.com/rundeck/packaging/main/scripts/rpm-setup.sh 2> /dev/null | bash -s rundeck

- name: "Instala o rundeck"
  become: true
  shell: yum install rundeck -y

- name: "Update"
  become: true
  shell: yum update -y


- name: "Comenta linha de filesystem no rundeck"
  become: true
  shell: sed -i '/projectsStorageType/s/^/#/g' /etc/rundeck/rundeck-config.properties

- name: "Adiciona o hostname no arquivo"
  become: true
  shell: echo "rundeck.projectsStorageType=filesystem" >> /etc/rundeck/rundeck-config.properties

- name: "Comenta linha de host no rundeck"
  become: true
  shell: sed -i '/localhost/s/^/#/g' /etc/rundeck/rundeck-config.properties

- name: "Adiciona o hostname no arquivo"
  become: true
  shell: echo "grails.serverURL=http://rundeck.dns.br" >> /etc/rundeck/rundeck-config.properties

- name: "Reinicia o serviço"
  become: true
  shell: systemctl restart rundeckd

- name: "Enable no serviço"
  become: true
  shell: systemctl enable rundeckd

- name: "Copia os arquivos"
  become: true
  shell: "cp -a /home/centos/.ssh/* /var/lib/rundeck/.ssh/"

- name: "da permissão"
  become: true
  shell: "chown -R rundeck:rundeck /var/lib/rundeck/.ssh/"

- name: "da permissão"
  become: true
  shell: ssh-keygen -p -m PEM -f /var/lib/rundeck/.ssh/id_rsa -N ''

- name: "Cria o caminho"
  become: true
  shell: "mkdir -p /etc/rundeck/nodes/"

- name: Copy id_rsa
  become: yes
  copy:
    src: files/sourcefile.yaml
    dest: /etc/rundeck/nodes/sourcefile.yaml
    owner: rundeck
    group: rundeck
    mode: '0777'

- name: "Cria o caminho"
  become: true
  shell: "chown -R rundeck:rundeck /etc/rundeck/nodes/"