---
- name: Definição localhost
  hosts: localhost
  connection: local 
  tasks:
  - name: "Add Docker’s official GPG key"
    become: true
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  
  - name: "Add Docker’s official GPG key"
    become: true
    shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: "Install Docker Engine"
    become: true
    shell: apt-get update -y

  - name: "Install Docker Engine"
    become: true
    shell: apt-get install docker-ce docker-ce-cli containerd.io -y
  