---
- hosts: all
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: "Instalação de pacotes desejados"
      become: true
      apt:
        name: ["mysql-server", "php", "apache2", "phpmyadmin", "python3-pip"]
        state: latest

    - name: Make sure pymysql is present
      become: true
      pip:
        name: pymysql
        state: present

    - name: Altera o usuário ROOT mysql para permitir conexão
      become: true
      shell: mysql --user="root" --password="root" --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'; flush privileges;"

    # - name: Reinicia mysql service
    #   become: true
    #   shell: service mysql restart

    - name: "Cria um banco de dados no Mysql"
      become: true
      mysql_db:
        name: xamppdb
        state: present
        login_password: root

    - name: "Define um usuário para modificar o banco xamppdb"
      become: true
      mysql_user:
        login_user: root
        login_password: root
        name: xamppdb 
        state: present
        priv: 'xamppdb.*:ALL'