Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    
    config.vm.provider "virtualbox" do |v|
        v.memory= 1024
        v.cpus = 1
    end

    config.vm.define "xampp" do |xampp|
        xampp.vm.network "public_network", ip: "10.1.1.120"
        #xampp.vm.provision "shell", inline: "sudo echo /vagrant/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf'"
    end
end