---
- name: "Instalação dos pacotes básicos"
  dnf:
    name:
      - "{{ epel_package }}"
      - "{{ utils_package }}"
      - "{{ net_package }}"
      - "{{ curl_package }}"
      - "{{ wget_package }}"
      - "{{ java_package }}"
    state: latest
    update_cache: yes

- name: "Verifica a instalação dos pacotes básicos"
  dnf:
    name:
      - "{{ epel_package }}"
      - "{{ utils_package }}"
      - "{{ net_package }}"
      - "{{ curl_package }}"
      - "{{ wget_package }}"
      - "{{ java_package }}"
    state: present

# DNS
- name: "[WORKAROUND (CENTOS 8)]: Altera o DNS da máquina"
  shell: echo "nameserver 192.168.2.200" > /etc/resolv.conf; echo "nameserver 192.168.2.1" >> /etc/resolv.conf;  chattr +i /etc/resolv.conf;

- name: "Adiciona o usuário '{{my_user}}', e o inclui ao grupo 'wheel'"
  user:
    name: "{{my_user}}"
    shell: /bin/bash
    group: wheel
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    append: yes

- name: "Cria as chaves do usuário"
  become_user: "{{my_user}}"
  copy:
    src: files/authorized_keys
    dest: /home/{{my_user}}/.ssh/authorized_keys
    owner: "{{my_user}}"
    group: wheel
    mode: "0600"

- name: "Atualiza permissão /home/{{my_user}}/.ssh/"
  become_user: "{{my_user}}"
  shell: chmod 700 -R /home/"{{my_user}}"/.ssh/

- name: Atualiza permissão /home/"{{my_user}}"/.ssh/
  become_user: "{{my_user}}"
  shell: chown "{{my_user}}":wheel -R /home/"{{my_user}}"/.ssh/
