---
- hosts: all
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Download kubeadm config images
      shell: kubeadm config images pull

  tasks:
    - name: Apped /etc/hostname 
      shell: echo "{{ k8smaster_hostname }}" > /etc/hostname 

    - name: Reboot the machine
      shell: "sleep 5 && reboot"

      async: 1
      poll: 0

    - name: Wait for the machine to come back online
      wait_for_connection:
        connect_timeout: 300
        sleep: 5
        delay: 5
        timeout: 300

  ###---- Swarm
    - name: Docker Swarm init
      shell: docker swarm init --advertise-addr 192.168.2.4
    
    - name: Creates join script swarm.sh
      copy:
        dest: /home/vagrant/swarm.sh
        content: |
          #!/bin/bash
          docker swarm join \
            --token change_your_token_here \
            192.168.2.4:2377

    - name: Load vars
      shell: docker swarm join-token --quiet worker
      register: ps
      # Print the shell task's stdout.
    - debug: msg={{ ps.stdout }}

    # Print all contents of the shell task's output.
    - debug: var=ps

    - name: replace script swarm.sh
      shell: sed -i "s/\bchange_your_token_here\b/{{ ps.stdout }} /g" swarm.sh 

  ###---- K8s
    - name: Kubeinit
      shell: |
        kubeadm init \
          --apiserver-advertise-address={{ k8smaster_ip }} \
          --apiserver-cert-extra-sans={{ k8smaster_ip }} \
          --pod-network-cidr=10.10.0.0/16 \
          --node-name {{ k8smaster_hostname }} \
          --ignore-preflight-errors Swap

    - name: "Creates dir at /home/vagrant/.kube"
      file:
        path: /home/vagrant/.kube
        owner: vagrant
        group: vagrant
        mode: "0750"
        remote_src: yes
        state: directory

    - name: Copy override file (exposes to 0.0.0.0)
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: "0750"

    - name: Kube apply Calico
      sudo_user: vagrant
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

    - name: Allow master node to execute pods
      sudo_user: vagrant
      shell: kubectl label node {{ k8smaster_hostname }} node-role.kubernetes.io/worker=worker-new

    - name: Creates join scripts
      sudo_user: vagrant
      shell: echo "#!/bin/bash" > ~/join.sh

    - name: Append join script
      sudo_user: vagrant
      shell: kubeadm token create --print-join-command >> ~/join.sh