[template]
src = "Vagrantfile.tmpl"
dest = "/tmp/confd/vagrant/dockerwkr3/Vagrantfile"
keys = [
    "/name/machine/6",
    "/cpu/machine/6",
    "/ram/machine/6",
    "/ip/machine/6",
    "/network/adapter",
]