Vagrant.configure("2") do |config|
    
    #dockermanager
    config.vm.define "manager" do |manager|
        # manager.vm.box = "ubuntu/focal64"
        manager.vm.box = "centos/8"
        manager.vm.synced_folder ".", "/vagrant", disabled: true
        manager.vbguest.no_remote = true
        manager.vbguest.auto_update = false
        manager.vm.network "public_network", ip: "192.168.2.20"
        manager.vm.provider "virtualbox" do |v|     
            v.memory= 1024
            v.cpus = 1
            v.name = "manager"
        end
    end

    #dockerworker01
    config.vm.define "worker01" do |worker01|
        worker01.vm.box = "centos/8"
        worker01.vm.synced_folder ".", "/vagrant", disabled: true
        worker01.vbguest.no_remote = true
        worker01.vbguest.auto_update = false
        worker01.vm.network "public_network", ip: "192.168.2.21"
        worker01.vm.provider "virtualbox" do |v|     
            v.memory= 1024
            v.cpus = 1
            v.name = "worker01"
        end
    end

    #dockerworker02
    config.vm.define "worker02" do |worker02|
        worker02.vm.box = "centos/8"
        worker02.vm.synced_folder ".", "/vagrant", disabled: true
        worker02.vbguest.no_remote = true
        worker02.vbguest.auto_update = false
        worker02.vm.network "public_network", ip: "192.168.2.22"
        worker02.vm.provider "virtualbox" do |v|     
            v.memory= 1024
            v.cpus = 1
            v.name = "worker02"
        end
    end
end