Vagrant.configure("2") do |config|

  #PWSERVER
    config.vm.define "pwserver" do |pwserver|
        pwserver.vm.box = "ubuntu/focal64"
        pwserver.vm.synced_folder ".", "/vagrant", disabled: true
        pwserver.vbguest.no_remote = true
        pwserver.vbguest.auto_update = false
        pwserver.vm.network "public_network", ip: "192.168.1.13"
        pwserver.vm.provider "virtualbox" do |v|
            v.check_guest_additions = false
            v.memory= 8192
            v.cpus = 4
            v.name = "pwserver"
        end  
    end      
end
